---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/build-timestamp: 2022-06-10 - 11:53:48 +0000
  labels:
    app.kubernetes.io/name: cave
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  name: cave
spec:
  ports:
    - name: http
      nodePort: 30762
      port: 80
      targetPort: 8080
  selector:
    app.kubernetes.io/name: cave
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.quarkus.io/build-timestamp: 2022-06-10 - 11:53:48 +0000
  labels:
    app.kubernetes.io/name: cave
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  name: cave
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: cave
      app.kubernetes.io/version: 1.0.0-SNAPSHOT
  template:
    metadata:
      annotations:
        app.quarkus.io/build-timestamp: 2022-06-10 - 11:53:48 +0000
      labels:
        app.kubernetes.io/name: cave
        app.kubernetes.io/version: 1.0.0-SNAPSHOT
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: 192.168.59.100:2376/presentation/cave:latest
          imagePullPolicy: IfNotPresent
          name: cave
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
